#!/usr/bin/python
# _*_ coding: utf-8 _*_

import sys
import os
import MySQLdb
import sys
import DBObject


from DBDrive import DBDrive
from DBCoordinate import DBCoordinate
from DBDrive import DBDrive
from chrispwd import getUserName
from chrispwd import getPassword

def getMySqlConnection(theDBName):
  return MySQLdb.Connection(user=getUserName(), passwd=getPassword(), db=theDBName, host='localhost')

con = getMySqlConnection("djangosite")
#con.autocommit(True);

def createLineStringKML(theDBDrive, theCoords, theOutFile):
  print( "Generating KML for " + theDBDrive.driveid)
  f = open(theOutFile,"w+")
  f.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>" + os.linesep)
  f.write("<!-- Byway KML Generated by BywayExplorer https://play.google.com/store/apps/details?id=com.csf.bywayexplorer -->")
  f.write("<kml xmlns=\"http://www.opengis.net/kml/2.2\">" + os.linesep)
  f.write("<Document>" + os.linesep)
  f.write("<name>" + theDBDrive.driveName + "</name>")
  
  i = 0
  for coords in theCoords:
    f.write("<Placemark>" + os.linesep)
    f.write("<name>" + theDBDrive.driveName + "_" + str(i) + "</name>" + os.linesep)
    f.write("<description>" + theDBDrive.shortDescription + "</description>" + os.linesep)
    f.write("<LineString>" + os.linesep)
    f.write("<altitudeMode>clampToGround</altitudeMode>" + os.linesep)
    f.write("<tessellate>1</tessellate>" + os.linesep)
    f.write("<coordinates>" + os.linesep) 
    for c in coords:
      lat = c["latitude"]
      lon = c["longitude"]
      ll = (lon,lat,0)
      f.write(str(lon) + "," + str(lat) + ",0 ")
    f.write("</coordinates></LineString>" + os.linesep)    
    f.write("</Placemark>")
    i+=1
    
  f.write("</Document> </kml>")
  f.close()
  
  
try:
  totalRequests = 0
  cur = con.cursor(MySQLdb.cursors.DictCursor)
  cur.execute("SELECT * FROM bywayexplorer_drive")
  driveRows = cur.fetchall()
  
  driveIndex = 0
  for driveRow in driveRows:
    driveid = driveRow["driveid"]
    drive = DBDrive()
    drive.setValues(driveRow)
    outFile = "kml_" + driveid + ".kml"
    if (not os.path.exists(outFile)):
      print("SELECT distinct subRoute from bywayexplorer_coordinate WHERE driveid = '" + driveid + "' ORDER BY subRoute")
      cur.execute("SELECT distinct subRoute from bywayexplorer_coordinate WHERE driveid = '" + driveid + "' ORDER BY subRoute")
      subRoutes = cur.fetchall()
      allCoords = []
      for subRoute in subRoutes:
        print ("SELECT * FROM bywayexplorer_coordinate WHERE driveid='" + driveid + "' AND subRoute = " + str(subRoute["subRoute"]) + " ORDER BY routeOrder")
        cur.execute("SELECT * FROM bywayexplorer_coordinate WHERE driveid='" + driveid + "' AND subRoute = " + str(subRoute["subRoute"]) + " ORDER BY routeOrder")
        coords = cur.fetchall()
        allCoords.append(coords)
        
      createLineStringKML(drive,allCoords,outFile)  
    else:
      print( "File Already Exists: " + outFile)
    driveIndex = driveIndex + 1
    #if (driveIndex > 0):
     # break
  
except MySQLdb.Error, e:
  print "Error %d: %s" % (e.args[0],e.args[1])
  sys.exit(1)
